{% set name = "llamaindex-py-client" %}
{% set version = "0.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llamaindex_py_client-{{ version }}.tar.gz
  sha256: 73f74792bb8c092bae6dc626627a09ac13a099fa8d10f8fcc83e17a2b332cca7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pydantic >=1.10
    - httpx >=0.20.0

test:
  imports:
    - llama_index_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://llamaindex.ai
  summary: API definitions for llama-index
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
